resources:
- manager.yaml

generatorOptions:
  disableNameSuffixHash: true

configMapGenerator:
- files:
  - controller_manager_config.yaml
  name: manager-config
- files:
  - Dockerfile=SonataFlow-Builder.containerfile
  literals:
  - DEFAULT_WORKFLOW_EXTENSION=.sw.json
  name: builder-config
- files:
  - controllers_cfg.yaml
  name: controllers-config

apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
images:
- digest: sha256:05f83eb018e18141fef961a6259fccd3ae0c25dad4c626e0ec09a20fadf78c3a
  name: controller
  newName: registry.redhat.io/openshift-serverless-1/logic-rhel8-operator
# Patching the manager deployment file to add an env var with the operator namespace in
patchesJson6902:
- patch: |-
    - op: add
      path: /spec/template/spec/containers/0/env
      value:
        - name: POD_NAMESPACE
          valueFrom:
            fieldRef:
              fieldPath: metadata.namespace
  target:
    group: apps
    kind: Deployment
    name: controller-manager
    namespace: system
    version: v1
